name: Cypress in Docker (Chrome)

on:
  push:
    branches: [ "cypress-setup" ]
  pull_request:
    branches: [ "cypress-setup" ]

jobs:
  cypress:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Run Cypress (Chrome)
        run: npx cypress run --browser chrome
